### ISSUE TITLE
currently not possible to issue token?  

### ISSUE THREAD

**Issue by TOMOAKI12345** [Colored-Coins/Colored-coins-add-on-for-Copay#10]
after 

```
npm start 
foreman start -f client/bower_components/copay-colored-coins-plugin/Procfile
```

can't see the asset issuance button as the web wallet does.

**Comment by troggy** [comment]
Thanks for your interest.

This addon requires extra features from Copay and BWS to be supported. Some of these features aren't pulled yet in Copay and BWS master branches, that's why addon doesn't work properly and you will need extra setup - see below. 

You can use the following branches to make it work:
Copay: https://github.com/troggy/copay/tree/wip
Bitcore Wallet Service: https://github.com/troggy/bitcore-wallet-service/tree/wip

Yes, you will need to set up your own BWS server using above code branch or use the [BWS instance](http://ec2-52-28-205-185.eu-central-1.compute.amazonaws.com:3232/bws/api) from copay.coloredcoins.org.

Branches above contain all the pending features merged into master and this code is used for copay.coloredcoins.org. Full list of pending features is [here](https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/blob/master/STATUS.md).

**Comment by troggy** [comment]
@TOMOAKI12345 how is your progress with this addon? Let me know if you still have issues with setting it up

**Comment by TOMOAKI12345** [comment]
@troggy currently I haven't tried it yet. but now I'm going to make crowdsale application using coloredcoin libraries. please help us when we stuck.

**Comment by Marksmargon** [comment]
How can we help?

**Comment by TOMOAKI12345** [comment]
@troggy  I uploaded current repo here, could you advice the missing point ? 
https://github.com/TOMOAKI12345/copay-coloredcoin/issues/1

**Comment by troggy** [comment]
@TOMOAKI12345 I've added more details to setup instructions: https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/blob/master/README.md

You are missing all the points except maybe point 5 which is done partially. E.g. you are not using custom Copay as advised in step 1 (Copay from master branch doesn't have all the feature merged yet), addon module is not registered with Copay (step 3)

I've made a [branch with steps 1 to 6 incorporated](https://github.com/troggy/copay/tree/colored), you can use it and do the rest of the setup by yourself. Don't forget that addon also needs custom BWS for the same reasons (see step 1).
